server:
    port: 8060
spring:
    application:
        name: microservice-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/wuyunan/springboot_demo/     # 配置git仓库的地址
                    search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
        discovery:
            enabled: true
            service-id: config-server
eureka:
    client:
        serviceUrl:
            defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka
    instance:
        preferIpAddress: true