version: "3"

services:
  demo:
    image: wuyunan/spring-boot-vultr
    container_name: spring-boot-vultr
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      #      - rabbitmq
    networks:
      - springnet

  mysql:
    image: mysql:8.0.13
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    command:
      --max_allowed_packet=32505856
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - springnet
      #    redis:
      ##      image: redis:4.0.12
      ##      container_name: redis-master
      ##      restart: always
      ##      networks:
      ##        - springnet

#    mongo:
#      image: mongo:latest
#      restart: always
#      ports:
#      - "27017:27017"
#      volumes:
#      - '/srv/docker/helloserver/mongo:/data/db:Z'
#      networks:
#      - springnet

#    rabbitmq:
#      image: rabbitmq:management
#      ports:
#      - "5672:5672"
#      - "15672:15672"
#      networks:
#      - apinet

networks:
  springnet:
