version: "3"

services:
    peer1:
        image: wuyunan/microservice-discovery-eureka
        container_name: microservice-discovery-eureka
        ports:
            - "8761:8761"
        environment:
            - spring.profiles.active=peer1
        networks:
            - csnet

    peer2:
        image: wuyunan/microservice-discovery-eureka
        container_name: microservice-discovery-eureka2
        ports:
            - "8762:8762"
        environment:
            - spring.profiles.active=peer2
        networks:
            - csnet

    microservice-gateway-zuul:
        hostname: zuul
        image: wuyunan/microservice-gateway-zuul
        container_name: microservice-gateway-zuul
        ports:
            - "8051:8051"
        networks:
            - csnet

    microservice-provider-user:
        hostname: feign
        image:  wuyunan/microservice-provider-user
        container_name: microservice-provider-user
        ports:
            - "8000:8000"
        environment:
                    - spring.profiles.active=profile1
        networks:
            - csnet
    microservice-provider-user2:
        hostname: feign
        image:  wuyunan/microservice-provider-user
        container_name: microservice-provider-user2
        ports:
            - "8001:8001"
        environment:
            - spring.profiles.active=profile2
        networks:
            - csnet

    microservice-consumer-movie-feign:
        hostname: feign
        image:  wuyunan/microservice-consumer-movie-feign
        container_name: microservice-consumer-movie-feign
        ports:
            - "8022:8022"
        networks:
            - csnet
networks:
    csnet:
