  version: "3"

  services:
    api:
      image: springio/gs-spring-boot-docker
      container_name: spring-boot-demo
      restart: always
      depends_on:
      - mongo
#      - rabbitmq

      ports:
      - "8080:8080"
      networks:
      - springnet

    mongo:
      image: mongo:4.0.2
      restart: always
      ports:
      - "27017:27017"
      volumes:
      - '/srv/docker/helloserver/mongo:/data/db:Z'
      networks:
      - springnet

#    rabbitmq:
#      image: rabbitmq:management
#      ports:
#      - "5672:5672"
#      - "15672:15672"
#      networks:
#      - apinet

  networks:
    springnet:
