server:
    port: 8051
spring:
    application:
        name: microservice-gateway-zuul
eureka:
    client:
        serviceUrl:
            defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka
#    instance:
#        preferIpAddress: true
zuul:
    routes:
        microservice-provider-user: /users/**
