jwt:
    authpath: auth
    authrefresh: refresh
    header: Authorization
    tokenExpiredMs: 604800000
    tokenSecret: qingteng

#logging:
#    level:
#        org:
#            hibernate: INFO
#            hibernate.SQL: debug
#            springframework: 'OFF'
#            springframework.web: ERROR
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
    http:
        multipart:
            enabled: false
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
                hbm2ddl:
                    auto: update
                    import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    profiles:
        active: demo
    servlet:
        multipart:
            max-file-size: 128KB
            max-request-size: 128KB

    # activiti default configuration
    activiti:
        database-schema-update: true
        check-process-definitions: true
        process-definition-location-prefix: classpath:/processes/
        #    process-definition-location-suffixes:
        #      - **.bpmn
        #      - **.bpmn20.xml
        history-level: full
swagger:
    enable: true

server:
    port: 80


# s3 test \u8D26\u53F7
amazonProperties:
    endpointUrl: https://s3.cn-north-1.amazonaws.com.cn
    accessKey: AKIAOQCXGAVSNIFF2LEQ
    secretKey: 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
    bucketName: crowdsource-uploaded-test
    region: cn-north-1

sms:
    enabled: false
    validate.max: 999
    sign-name: \u4E92\u751F\u4FE1\u606F
    ali:
        access-key-id: LTAIRstlNrvlUOMg
        template-code: SMS_149980229