spring:
    application:
        name: dubbo-spring-boot-starter
    dubbo:
        application:
            name: demo-provider
        base-package: com.qingteng.msg.service      # dubbo服务发布者所在的包
        registry:
            address: 192.168.1.170              # zookeeper注册中心的地址
            port: 2181                           # zookeeper注册中心的端口
        protocol:
            name: dubbo
            serialization: hessian2
        provider:
            timeout: 10000 # 配置全局调用服务超时时间，dubbo默认是1s，肯定不够用呀
            retries: 3 # 重试3次
            delay: -1