server:
    port: 8041
spring:
    application:
        name: microservice-hystrix-turbine
eureka:
    client:
        service-url:
            defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka
    instance:
        prefer-ip-address: true
turbine:
    # 要监控的微服务列表，多个用,分隔
    appConfig: microservice-consumer-movie-ribbon-with-hystrix,microservice-consumer-movie-feign
    clusterNameExpression: "'default'"