server:
    port: 8011
spring:
    application:
        name: microservice-consumer-movie
eureka:
    client:
        serviceUrl:
            defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka
    instance:
        preferIpAddress: true


user:
    userServiceUrl: http://localhost:8000/users/